// GLOBAL ACTION TYPES
export const TOGGLE_DARK_MODE = 'TOGGLE_DARK_MODE'

// HTTP
export const HTTP_REQUEST = 'HTTP/REQUEST'
export const HTTP_SUCCESS = 'HTTP/SUCCESS'
export const HTTP_FAILURE = 'HTTP/FAILURE'

// SESSION
export const SESSION_FETCH = 'SESSION/FETCH'
export const SESSION_SET = 'SESSION/SET'
export const SESSION_RESET = 'SESSION/RESET'
