// GLOBAL ACTION TYPES
export const TOGGLE_DARK_MODE = 'TOGGLE_DARK_MODE'

// HTTP
export const HTTP_REQUEST = 'HTTP/REQUEST'
export const HTTP_SUCCESS = 'HTTP/SUCCESS'
export const HTTP_FAILURE = 'HTTP/FAILURE'

// SESSION
export const SESSION_FETCH = 'SESSION/FETCH'
export const SESSION_SET = 'SESSION/SET'
export const SESSION_RESET = 'SESSION/RESET'

// POSTS
export const POSTS_FETCH = 'POSTS/FETCH'
export const POSTS_RETRIEVE = 'POSTS/RETRIEVE'
export const POSTS_ADD = 'POSTS/ADD'
export const POSTS_SET = 'POSTS/SET'
export const POSTS_SET_INFO = 'POSTS/SET_INFO'
export const POSTS_GET = 'POSTS/GET'
export const POSTS_RESET = 'POSTS/RESET'
